/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Temperature = IDL.Record({
  'value' : IDL.Int,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addTemperature' : IDL.Func([IDL.Int], [], []),
  'getTemperatures' : IDL.Func([], [IDL.Vec(Temperature)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Temperature = IDL.Record({ 'value' : IDL.Int, 'timestamp' : IDL.Int });
  
  return IDL.Service({
    'addTemperature' : IDL.Func([IDL.Int], [], []),
    'getTemperatures' : IDL.Func([], [IDL.Vec(Temperature)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };